# Generated by Django 5.2.6 on 2025-09-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(help_text='Módulo al que pertenece (CRM, Ecommerce, etc.)', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_extendido', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permiso Extendido',
                'verbose_name_plural': 'Permisos Extendidos',
            },
        ),
        migrations.CreateModel(
            name='RolExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_extendido', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol Extendido',
                'verbose_name_plural': 'Roles Extendidos',
            },
        ),
    ]
