services:
   backend:
     container_name: backend-container
     build: ./backend
     volumes:
       - ./Backend:/usr/app/backend
     ports:
       - 8000:8000
     networks:
       - app-network

   frontend:
     container_name: frontend-container
     build: ./frontend
     environment:
      - CHOKIDAR_USEPOLLING=true
     volumes:
       - ./frontend:/usr/app/frontend
     ports: 
       - 4000:4000
     depends_on:
       - backend
     networks:
       - app-network

networks:
  app-network:
    driver: bridge

