# Generated by Django 5.2.6 on 2025-11-18 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('CORREO', 'Correo Electrónico'), ('WHATSAPP', 'Mensaje (WhatsApp)'), ('REUNION', 'Reunión'), ('OTRO', 'Otro')], max_length=20)),
                ('notas', models.TextField()),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ('-fecha_actividad',),
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_ecommerce', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_crm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Venta de uniformes Empresa X', max_length=255)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('CALIFICACION', 'Calificación'), ('PROPUESTA', 'Propuesta Presentada'), ('NEGOCIACION', 'En Negociación'), ('GANADA', 'Cerrada (Ganada)'), ('PERDIDA', 'Cerrada (Perdida)')], default='CALIFICACION', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm_preventa.contacto')),
                ('pedido_ecommerce', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidad_crm', to='pedidos.pedido')),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_propias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Potencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('fuente', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('REFERIDO', 'Referido'), ('TIENDA_FISICA', 'Tienda Física'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('CALIFICADO', 'Calificado (Se convirtió en Contacto)'), ('NO_CALIFICADO', 'No Calificado')], default='NUEVO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potenciales_propios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='potencial_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_preventa.potencial'),
        ),
    ]
