# Generated by Django 5.2.6 on 2025-11-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_preventa', '0001_initial'),
    ]

    operations = [
        # Remove the old UUID field
        migrations.RemoveField(
            model_name='actividad',
            name='object_id',
        ),
        # Add it back as PositiveIntegerField
        migrations.AddField(
            model_name='actividad',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
