# Generated by Django 5.2.6 on 2025-10-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_imagenproducto_url_alter_imagenproducto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
