# Generated by Django 5.2.6 on 2025-10-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_imagenproducto_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='main_image',
        ),
    ]
