# Generated by Django 5.2.6 on 2025-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_imagenproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
