# Generated by Django 5.2.6 on 2025-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='url',
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='boutique/productos'),
        ),
    ]
