# Generated by Django 5.2.6 on 2025-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='boutique/productos'),
        ),
    ]
