# Generated by Django 5.2.6 on 2025-10-22 03:36

import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_direccion_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['-es_predeterminada'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='direccion',
            name='instrucciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='nombre_destinatario',
            field=models.CharField(default='desconocido', help_text='Nombre de la persona que recibirá el pedido.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='acepta_marketing',
            field=models.BooleanField(default=False, help_text='Indica si el usuario acepta recibir correos de marketing.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su correo electrónico.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token único para la verificación de email.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero_documento_fiscal',
            field=models.CharField(blank=True, help_text='CI, NIT, RUC, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal o de empresa para facturación', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_documento_fiscal',
            field=models.CharField(blank=True, choices=[('CI', 'Cédula de Identidad'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=django_countries.fields.CountryField(default='BO', max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Teléfono de contacto para la entrega.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
