# Generated by Django 5.2.6 on 2025-11-19 09:15

from django.db import migrations


def add_is_verified_if_not_exists(apps, schema_editor):
    """
    Añade la columna is_verified si no existe en la tabla users_user
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='users_user' AND column_name='is_verified'
        """)
        if not cursor.fetchone():
            # La columna no existe, la creamos
            cursor.execute("""
                ALTER TABLE users_user 
                ADD COLUMN is_verified BOOLEAN DEFAULT TRUE NOT NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_direccion_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_is_verified_if_not_exists, migrations.RunPython.noop),
    ]
