# Generated by Django 5.2.6 on 2025-11-19 09:27

from django.db import migrations, connection


def ensure_is_verified_column(apps, schema_editor):
    """
    Asegura que la columna is_verified exista en users_user
    Usa una query que funciona con el esquema actual del tenant
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna existe usando pg_attribute
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM pg_attribute 
                WHERE attrelid = 'users_user'::regclass 
                AND attname = 'is_verified' 
                AND NOT attisdropped
            );
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            print(f"Añadiendo columna is_verified en esquema: {connection.schema_name}")
            cursor.execute("""
                ALTER TABLE users_user 
                ADD COLUMN is_verified BOOLEAN DEFAULT TRUE NOT NULL;
            """)
        else:
            print(f"Columna is_verified ya existe en esquema: {connection.schema_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20251119_0515'),
    ]

    operations = [
        migrations.RunPython(ensure_is_verified_column, migrations.RunPython.noop),
    ]
