# Generated by Django 5.2.6 on 2025-11-19 09:35

from django.db import migrations, connection
import uuid


def ensure_verification_uuid_and_acepta_marketing(apps, schema_editor):
    """
    Asegura que las columnas verification_uuid y acepta_marketing existan
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar verification_uuid
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM pg_attribute 
                WHERE attrelid = 'users_user'::regclass 
                AND attname = 'verification_uuid' 
                AND NOT attisdropped
            );
        """)
        exists_uuid = cursor.fetchone()[0]
        
        if not exists_uuid:
            print(f"Añadiendo columna verification_uuid en esquema: {connection.schema_name}")
            cursor.execute("""
                ALTER TABLE users_user 
                ADD COLUMN verification_uuid UUID DEFAULT gen_random_uuid() NOT NULL;
            """)
        else:
            print(f"Columna verification_uuid ya existe en esquema: {connection.schema_name}")
        
        # Verificar acepta_marketing
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM pg_attribute 
                WHERE attrelid = 'users_user'::regclass 
                AND attname = 'acepta_marketing' 
                AND NOT attisdropped
            );
        """)
        exists_marketing = cursor.fetchone()[0]
        
        if not exists_marketing:
            print(f"Añadiendo columna acepta_marketing en esquema: {connection.schema_name}")
            cursor.execute("""
                ALTER TABLE users_user 
                ADD COLUMN acepta_marketing BOOLEAN DEFAULT FALSE NOT NULL;
            """)
        else:
            print(f"Columna acepta_marketing ya existe en esquema: {connection.schema_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20251119_0527'),
    ]

    operations = [
        migrations.RunPython(ensure_verification_uuid_and_acepta_marketing, migrations.RunPython.noop),
    ]
