# Generated by Django 5.2.6 on 2025-11-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_is_verified_and_more'),
        ('users', '0009_auto_20251119_0535'),
    ]

    operations = [
    ]
