# Generated by Django 5.2.6 on 2025-10-19 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('envio', 'Envío'), ('facturacion', 'Facturación')], default='envio', max_length=20)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('linea1', models.CharField(max_length=255, verbose_name='Dirección Línea 1')),
                ('linea2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Línea 2')),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(default='Bolivia', max_length=50)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.URLField(blank=True, help_text='URL de la imagen de perfil (ej. de Cloudinary)', max_length=500, null=True)),
                ('preferencias_ui', models.JSONField(blank=True, default=dict, help_text='Configuraciones de UI como tema, fuente, etc.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
