# Generated by Django 5.2.6 on 2025-10-07 20:39

from django.db import migrations
from django.utils import timezone
from ..models import Tenant

class Migration(migrations.Migration):
    
    def create_initial_tenants(apps, schema_editor):
        Tenant.objects.create(name='localhost-1', domain='localhost', created_at=timezone.now())
        Tenant.objects.create(name='localhost-2', domain='127.0.0.1', created_at=timezone.now())
        Tenant.objects.create(name='azure', domain='48.221.113.92', created_at=timezone.now())
        Tenant.objects.create(name='frontend', domain='frontend', created_at=timezone.now())

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_tenants),
    ]

