# Generated by Django 5.2.6 on 2025-11-18 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ACTIVO', 'Activo'), ('VIP', 'VIP'), ('RIESGO', 'En Riesgo')], default='NUEVO', max_length=20)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
                ('segmentos', models.ManyToManyField(blank=True, related_name='clientes', to='clientes.segmento')),
            ],
            options={
                'verbose_name': 'Cliente (Perfil 360)',
                'verbose_name_plural': 'Clientes (Perfiles 360)',
            },
        ),
    ]
